# Generated by Django 5.0.1 on 2024-02-08 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionslistings_active_auctionslistings_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionslistings',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 15, 23, 12, 318740, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionslistings',
            name='description',
            field=models.CharField(max_length=125),
        ),
    ]
