# Generated by Django 5.0.1 on 2024-02-20 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionslistings_winner_alter_auctionslistings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='auctionslistings',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 11, 22, 38, 949184, tzinfo=datetime.timezone.utc)),
        ),
    ]
