# Generated by Django 5.0.1 on 2024-02-23 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comments_comment_alter_auctionslistings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 18, 34, 5, 202786, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionslistings',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 18, 34, 5, 200785, tzinfo=datetime.timezone.utc)),
        ),
    ]
